### ISSUE TITLE
Fail in callback_phase

### ISSUE THREAD

**Issue by koshilife** [koshilife/omniauth-zoom#2]
refs:
https://github.com/omniauth/omniauth-oauth2/blob/master/lib/omniauth/strategies/oauth2.rb#L78

StackTrace
```
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:491:in `fail!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth-oauth2 (1.6.0) lib/omniauth/strategies/oauth2.rb:78:in `rescue in callback_phase'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth-oauth2 (1.6.0) lib/omniauth/strategies/oauth2.rb:66:in `callback_phase'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:238:in `callback_call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:189:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:192:in `call!'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/strategy.rb:169:in `call'
[c8ced95f-c685-42fb-a682-d43798c4db82] omniauth (1.9.1) lib/omniauth/builder.rb:45:in `call'
```

**Comment by koshilife** [comment]
refs
https://marketplace.zoom.us/docs/guides/auth/oauth
